From yanivomc/alpine-oraclejdk8:slim

ARG ARTIFACT_PATH=src
ENV DBURL=http://1.2.3.4

RUN echo ${ARTIFACT_PATH}

ENV ATF_JAR=spring-music.jar


WORKDIR /app
COPY ${ARTIFACT_PATH}/${ATF_JAR} .


EXPOSE 8080

CMD java -jar -Dspring.profiles.active=none ${ATF_JAR}
