version: "3"
services: 
  web:
    image: default_apache
    deploy: 
      replicas: 2
  lb:
    image: dockercloud/haproxy
    links: 
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

