version: '3'
services:
  consul:
    image: consul
    restart: unless-stopped
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 0.0.0.0:8500:8500
      - 0.0.0.0:8600:8600/udp
    networks:
      - consul
  workshop:
    image: workshop
    ports:
      - 0.0.0.0:8000:8000
    networks:
      - consul

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9092:9092
    networks:
     - consul

networks:
  consul:
