# First stage: Build
FROM node:18 AS builder
WORKDIR /app
COPY app .
RUN npm install

# Second stage: Production
FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=builder /app .
COPY --from=builder /app/node_modules ./node_modules
CMD ["node", "server.js"]
